### ISSUE TITLE
Alignment error accessing document meta data on SPARC64 with FreeBSD

### ISSUE THREAD

**Issue by patrickfrey** [patrickfrey/strus#33]
Starting program: /usr/home/abaumann/strus/tests/metaDataRestrictions/src/testMetaDataRestrictions 10 10 10
(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/home/abaumann/strus/src/utils/libstrus_utils.so.0.3]
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/local/lib/gcc48/libstdc++.so.6](no debugging symbols found)...Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/local/lib/gcc48/libgcc_s.so.1](no debugging symbols found)...(no debugging symbols found)...[New LWP 100070](no debugging symbols found)...[New Thread 41804400 (LWP 100070/testMetaDataRestric)]
__sparc_utrap: fatal memory address not aligned

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 41804400 (LWP 100070/testMetaDataRestric)]
0x0000000040ec0b88 in kill () from /lib/libc.so.7
(gdb) bt
#0  0x0000000040ec0b88 in kill () from /lib/libc.so.7

**Comment by andreasbaumann** [comment]
strus 0.3.2 compiles and tests run fine on SPARC64 FreeBsd.
Can be closed from my point of view.

**Comment by andreasbaumann** [comment]
retested on 0.4.3, all fine.
