### ISSUE TITLE
Strong license

### ISSUE THREAD

**Issue by dw** [patrickfrey/strus#38]
Hi there :)

I'm always overjoyed to discover some new full text search solution, especially one already shipping with a Python binding, however as a preferred go-to option while working commercially, the choice of GPL, and GPL 3 in particular pushes Strus lower in the list than e.g. the ancient CLucene, Groonga, or some out of process solution like Solr or ES.

IIRC in the past the Xapian guys have considered the GPL may have been a mistake, as it prevented the kind of adoptions that might have led to a much stronger ecosystem around their software, and they've been gradually trying to move to LGPL for more than half a decade now.

One needn't look further than Lucene to see how a liberal license can benefit an excellent design. No doubt you've considered this at length, but just in case you haven't, this is a short appeal for you to consider a more liberal license. :)

Thanks regardless, Strus looks awesome for much more than just full text search, I'll be keeping it in mind.

**Comment by patrickfrey** [comment]
I will think about changing the license.
Discussions about this issue are ongoing, also from other side.
The final decision about this issue is planned at the latest for end of march.
But most likely I will make a decision when publishing the next version of the Wikipedia demo search that will have a lot of improvements and will run on a competitive machine.

**Comment by patrickfrey** [comment]
We are intending to move to Mozilla Public License v2 (MPLv2).
The final decision will be made start of next week.

**Comment by patrickfrey** [comment]
We have changed the Strus software license from GPLv3 to Mozilla Public License v2 (MPLv2). 
(on current trunk, documentation, packages version >= 0.6.0)

**Comment by dw** [comment]
Hi Patrick,

This is amazing! Thanks, look forward to playing with it soon
