### ISSUE TITLE
wrong number of documents

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strus#58]
Inserted 2493 documents in a new index,
nof docs of strusInspect shows 2493.
If I reinsert the same documents I get 4986.

In storageTransaction.cpp I see:

```
 m_storage->declareNofDocumentsInserted( m_nof_documents);
```

without any checks whether the documents already existed before.

**Comment by andreasbaumann** [comment]
strusInsepct of attribute docid always shows 2493 documents.

**Comment by patrickfrey** [comment]
m_nof_documents is only incremented if the document id is not known yet. There might be a bug, but if, it is not so simple as it looks.

**Comment by andreasbaumann** [comment]
Tested on 32-bit/64-bit, same result.
Tested with 16 threads and with one thread, same result.

```
Total number of documents read: 102037
Total number of documents received: 102037
Total number of documents (re)indexed: 102037
Total number of documents skipped: 0
Terminating main thread.
curl -q http://localhost:8080/strus/index/stats/aza
{"result":"ok","stats":{"nof_docs":204074}}
```

Same effect. So this seems to be neither a locking issue or race nor a platform problem, there
is something wrong with the logic.

**Comment by patrickfrey** [comment]
fixed
