### ISSUE TITLE
valueIteratorInterface storage createDocIdIterator is weird to use

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strus#62]
If I don't call skip, is the iterator giving me docids from the beginning?
Is it returning deleted documents or not? Apparently not. Other iterators do (like iterating
the document number). This should maube be clarified.
What's the end condition when reaching EOF? Is the last element of the vector
containg an empty string?

An example of getting all docids:

```
std::vector<std::string> SearchIndex::getDocids( )
{
    boost::scoped_ptr<strus::ValueIteratorInterface> it;
    it.reset( m_storage->createDocIdIterator( ) );

    std::vector<std::string> res;
    std::vector<std::string> v;
    do {
        v = it->fetchValues( 1024 );
        res.insert( res.end( ), v.begin( ), v.end( ) );
    } while( v.size( ) > 0 && v[v.size( )] != "" );

    return res;
}
```

**Comment by patrickfrey** [comment]
The interface is indeed (as exception) a little bit awkward. 
'skip' puts the iterator to the first upperbound element of key.
fetchValues fetches the next N elements starting with this upperbound (see interface documentation).
With the maxNofElements you specify maximum number of elements to fetch.
The idea of this interface was driven by RPC and the fact that this iterator is also important in the RPC context. And there youe cannot affort roundtrips for every element returned.
