### ISSUE TITLE
highlighting an expression with complex token positions

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strus#71]
How can I access the actual positions of a match of for instance an expression
like `sequence("a","b", range=4, cardinality=0)`?
Do I get the positions of `a` and `b` if I'm iterating the posting in the summarizer?

**Comment by patrickfrey** [comment]
When iterating on the PostingIterator of the feature, you get the ordinal position of the first term in the matching sequence of each match. If you are interested in ordinal positions of other subexpressions, e.g. "b", you have to assign a variable to "b", when creating the feature. See QueryInterface::attachVariable( const std::string& name). The attached Variables get passed to the summarizer with the PostingIterator of the feature. The method SummarizationVariable::position() gives you the ordinal position of a subexpression for the current ordinal position of the feature posting iterator.

**Comment by andreasbaumann** [comment]
So for a phrase consisting of four words I have to define four variables?

**Comment by patrickfrey** [comment]
Yes, but you can use the same variable name 4 times
